ALLOWED_HOSTS = ["127.0.0.1"]
STRIPE_API_KEY = ""
GOOGLE_CLIENT_ID = "YOUR_CLIENT_ID"
GOOGLE_SECRET = "YOUR_SECRET_KEY"
GOOGLE_KEY = ""
MICROSOFT_CLIENT_ID = "YOUR_CLIENT_ID"
MICROSOFT_SECRET = "YOUR_SECRET_KEY"
MICROSOFT_KEY = ""