# Generated by Django 4.1.7 on 2023-02-18 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("paid", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Currencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbr for this currency (i.e. EUR)", max_length=64
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        help_text="Long name for this currency (i.e. Euro)",
                        max_length=64,
                    ),
                ),
                (
                    "relation_to_PLN",
                    models.PositiveSmallIntegerField(
                        help_text="Price in PLN for 1 in this currency"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="item",
            old_name="price",
            new_name="_price",
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="Ten wspaniały..", help_text="Description of the item"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
    ]
